name: run fitbit pipeline
on:
  schedule:
    - cron: '0 3 * * 1'  # sunday at 3 AM UTC
  workflow_dispatch:
    inputs:
      force_full_refresh:
        description: 'Force full refresh'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: set google credentials environment variable
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa_key.json" >> $GITHUB_ENV
          
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: install pipenv and dependencies
        run: |
          make install
          
      - name: write keyfile
        run: |
          cat << 'EOF' > $GOOGLE_APPLICATION_CREDENTIALS
          ${{ secrets.GCP_SVC_KEY }}
          EOF

      - name: run fitbit pipeline
        env:
          FORCE_FULL_REFRESH: ${{ inputs.force_full_refresh }}
          RUNTIME__LOG_LEVEL: "INFO"
        run: |
          pipenv run python -m pipelines.fitbit
          
      - name: remove keyfile
        if: always()
        run: |
          rm $GOOGLE_APPLICATION_CREDENTIALS

      - name: upload dlt state files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fitbit-pipeline-state
          path: |
            ~/.dlt/**/state.json
          retention-days: 7
