name: test dlt pipelines
on:
  pull_request:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - 'tests/**'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'Makefile'
  push:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  test-pipelines:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: set environment variables
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa_key.json" >> $GITHUB_ENV
          
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: install pipenv and dependencies
        run: |
          make install
          
      - name: write keyfile
        run: |
          cat << 'EOF' > $GOOGLE_APPLICATION_CREDENTIALS
          ${{ secrets.GCP_SVC_KEY }}
          EOF

      - name: run tests
        id: run_tests
        env:
          RUNTIME__LOG_LEVEL: "INFO"
        run: |
          make test-all

      - name: remove keyfile
        if: always()
        run: |
          rm $GOOGLE_APPLICATION_CREDENTIALS
          
      - name: upload coverage reports to Codecov
        if: steps.run_tests.outcome != 'skipped'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          
      - name: upload test results to Codecov
        if: steps.run_tests.outcome != 'skipped'
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./test-results-local.xml,./test-results-e2e.xml
