name: test dlt pipelines
on:
  pull_request:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - 'tests/**'
      - 'Pipfile'
      - 'Pipfile.lock'
  push:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  test-pipelines:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: install pipenv and dependencies
        run: |
          make install
          
      - name: set environment variables
        if: github.actor != 'dependabot[bot]'
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa_key.json" >> $GITHUB_ENV
          
      - name: write keyfile
        if: github.actor != 'dependabot[bot]'
        run: |
          cat << 'EOF' > $GOOGLE_APPLICATION_CREDENTIALS
          ${{ secrets.GCP_SVC_KEY }}
          EOF

      - name: install 1password cli
        if: github.actor != 'dependabot[bot]'
        uses: 1password/install-cli-action@v2

      - name: inject secrets using service account
        if: github.actor != 'dependabot[bot]'
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          make inject

      - name: run local tests
        id: run_local_tests
        env:
          RUNTIME__LOG_LEVEL: "INFO"
        run: |
          make test-local

      - name: run e2e tests
        id: run_e2e_tests
        if: github.actor != 'dependabot[bot]'
        env:
          RUNTIME__LOG_LEVEL: "INFO"
        run: |
          make test-e2e

      - name: remove keyfile
        if: always()
        run: |
          rm -f $GOOGLE_APPLICATION_CREDENTIALS
          
      - name: check if tests ran
        id: check_tests
        if: always()
        run: |
          if [ "${{ steps.run_local_tests.outcome }}" != "skipped" ] || [ "${{ steps.run_e2e_tests.outcome }}" != "skipped" ]; then
            echo "tests_ran=true" >> $GITHUB_OUTPUT
          else
            echo "tests_ran=false" >> $GITHUB_OUTPUT
          fi
          
      - name: upload coverage reports to Codecov
        if: steps.check_tests.outputs.tests_ran == 'true'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          
      - name: upload test results to Codecov
        if: steps.check_tests.outputs.tests_ran == 'true'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./test-results-local.xml,./test-results-e2e.xml
          report_type: test_results
